// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// applyDropoutMaskCpp
NumericMatrix applyDropoutMaskCpp(NumericMatrix data, NumericVector mask);
RcppExport SEXP darch_applyDropoutMaskCpp(SEXP dataSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mask(maskSEXP);
    __result = Rcpp::wrap(applyDropoutMaskCpp(data, mask));
    return __result;
END_RCPP
}
// ditherCpp
void ditherCpp(NumericMatrix data, NumericVector columnMask);
RcppExport SEXP darch_ditherCpp(SEXP dataSEXP, SEXP columnMaskSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type columnMask(columnMaskSEXP);
    ditherCpp(data, columnMask);
    return R_NilValue;
END_RCPP
}
// maxoutUnitCpp
void maxoutUnitCpp(NumericMatrix activations, NumericMatrix derivatives, int poolSize, NumericVector dropoutMask);
RcppExport SEXP darch_maxoutUnitCpp(SEXP activationsSEXP, SEXP derivativesSEXP, SEXP poolSizeSEXP, SEXP dropoutMaskSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type activations(activationsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type derivatives(derivativesSEXP);
    Rcpp::traits::input_parameter< int >::type poolSize(poolSizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dropoutMask(dropoutMaskSEXP);
    maxoutUnitCpp(activations, derivatives, poolSize, dropoutMask);
    return R_NilValue;
END_RCPP
}
// maxoutWeightUpdateCpp
void maxoutWeightUpdateCpp(NumericMatrix inc, int poolSize);
RcppExport SEXP darch_maxoutWeightUpdateCpp(SEXP incSEXP, SEXP poolSizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type inc(incSEXP);
    Rcpp::traits::input_parameter< int >::type poolSize(poolSizeSEXP);
    maxoutWeightUpdateCpp(inc, poolSize);
    return R_NilValue;
END_RCPP
}
// minimizeCpp
List minimizeCpp(NumericVector x, Function f, int length, double red, List dims, NumericMatrix data, NumericMatrix target, int epochSwitch, Function matMult);
RcppExport SEXP darch_minimizeCpp(SEXP xSEXP, SEXP fSEXP, SEXP lengthSEXP, SEXP redSEXP, SEXP dimsSEXP, SEXP dataSEXP, SEXP targetSEXP, SEXP epochSwitchSEXP, SEXP matMultSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< double >::type red(redSEXP);
    Rcpp::traits::input_parameter< List >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type epochSwitch(epochSwitchSEXP);
    Rcpp::traits::input_parameter< Function >::type matMult(matMultSEXP);
    __result = Rcpp::wrap(minimizeCpp(x, f, length, red, dims, data, target, epochSwitch, matMult));
    return __result;
END_RCPP
}
// normalizeWeightsCpp
void normalizeWeightsCpp(NumericMatrix weights, float bound);
RcppExport SEXP darch_normalizeWeightsCpp(SEXP weightsSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< float >::type bound(boundSEXP);
    normalizeWeightsCpp(weights, bound);
    return R_NilValue;
END_RCPP
}
