# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

applyDropoutMaskCpp <- function(data, mask) {
    .Call('darch_applyDropoutMaskCpp', PACKAGE = 'darch', data, mask)
}

ditherCpp <- function(data, columnMask) {
    invisible(.Call('darch_ditherCpp', PACKAGE = 'darch', data, columnMask))
}

maxoutUnitCpp <- function(activations, derivatives, poolSize, dropoutMask) {
    invisible(.Call('darch_maxoutUnitCpp', PACKAGE = 'darch', activations, derivatives, poolSize, dropoutMask))
}

maxoutWeightUpdateCpp <- function(inc, poolSize) {
    invisible(.Call('darch_maxoutWeightUpdateCpp', PACKAGE = 'darch', inc, poolSize))
}

minimizeCpp <- function(x, f, length, red, dims, data, target, epochSwitch, matMult) {
    .Call('darch_minimizeCpp', PACKAGE = 'darch', x, f, length, red, dims, data, target, epochSwitch, matMult)
}

normalizeWeightsCpp <- function(weights, bound) {
    invisible(.Call('darch_normalizeWeightsCpp', PACKAGE = 'darch', weights, bound))
}

