# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

applyDropoutMaskCpp <- function(data, mask) {
    .Call('_darch_applyDropoutMaskCpp', PACKAGE = 'darch', data, mask)
}

ditherCpp <- function(data, columnMask) {
    .Call('_darch_ditherCpp', PACKAGE = 'darch', data, columnMask)
}

exponentialLinearUnitCpp <- function(input, alpha) {
    .Call('_darch_exponentialLinearUnitCpp', PACKAGE = 'darch', input, alpha)
}

maxoutUnitCppParallel <- function(activations, derivatives, poolSize, dropoutMask) {
    invisible(.Call('_darch_maxoutUnitCppParallel', PACKAGE = 'darch', activations, derivatives, poolSize, dropoutMask))
}

maxoutUnitCpp <- function(activations, derivatives, poolSize, dropoutMask) {
    invisible(.Call('_darch_maxoutUnitCpp', PACKAGE = 'darch', activations, derivatives, poolSize, dropoutMask))
}

maxoutWeightUpdateCpp <- function(inc, poolSize) {
    invisible(.Call('_darch_maxoutWeightUpdateCpp', PACKAGE = 'darch', inc, poolSize))
}

minimizeCpp <- function(x, f, length, red, dims, data, target, epochSwitch, matMult) {
    .Call('_darch_minimizeCpp', PACKAGE = 'darch', x, f, length, red, dims, data, target, epochSwitch, matMult)
}

normalizeWeightsCpp <- function(weights, bound) {
    invisible(.Call('_darch_normalizeWeightsCpp', PACKAGE = 'darch', weights, bound))
}

rectifiedLinearUnitCpp <- function(input) {
    .Call('_darch_rectifiedLinearUnitCpp', PACKAGE = 'darch', input)
}

rpropGradientsCpp <- function(gg, gradients) {
    invisible(.Call('_darch_rpropGradientsCpp', PACKAGE = 'darch', gg, gradients))
}

rpropDeltaCpp <- function(gg, delta, inc, dec, minDelta, maxDelta) {
    invisible(.Call('_darch_rpropDeltaCpp', PACKAGE = 'darch', gg, delta, inc, dec, minDelta, maxDelta))
}

rpropDeltaWiRpropPlusCpp <- function(gg, deltaW, gradients, delta, newE, oldE) {
    invisible(.Call('_darch_rpropDeltaWiRpropPlusCpp', PACKAGE = 'darch', gg, deltaW, gradients, delta, newE, oldE))
}

sigmoidUnitCpp <- function(input) {
    .Call('_darch_sigmoidUnitCpp', PACKAGE = 'darch', input)
}

softmaxUnitCpp <- function(input) {
    .Call('_darch_softmaxUnitCpp', PACKAGE = 'darch', input)
}

softplusUnitCpp <- function(input) {
    .Call('_darch_softplusUnitCpp', PACKAGE = 'darch', input)
}

